# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.4
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
branches:
  only:
  - master
  - /v(\d+)\.(\d+)\.(\d+)/
codecov: true
